server:
  port: 8083


spring:
  application:
    name: HOSPITAL-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hospital_service_db
    username: postgres
    password: 1234
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

services:
  set-employment: http://USER-SERVICE/user/set-employment

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:https://127.0.0.1:8761/eureka/}
    instance:
      preferIpAddress: true

jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848567890iuyiu67567886578uyutuio7865467897654678965467uior678545
